/**
 * All 195 UN-recognized countries + a few territories.
 * flag(code) returns the emoji flag via regional indicator symbols.
 */

export interface Country {
  code: string;   // ISO 3166-1 alpha-2
  name: string;   // English name
  nameFr: string; // French name
}

/** Convert ISO code to emoji flag */
export function countryFlag(code: string): string {
  if (!code || code.length !== 2) return '🏳️';
  const upper = code.toUpperCase();
  return String.fromCodePoint(
    ...Array.from(upper).map(c => 0x1F1E6 + c.charCodeAt(0) - 65)
  );
}

export const COUNTRIES: Country[] = [
  { code: 'AF', name: 'Afghanistan', nameFr: 'Afghanistan' },
  { code: 'AL', name: 'Albania', nameFr: 'Albanie' },
  { code: 'DZ', name: 'Algeria', nameFr: 'Algérie' },
  { code: 'AD', name: 'Andorra', nameFr: 'Andorre' },
  { code: 'AO', name: 'Angola', nameFr: 'Angola' },
  { code: 'AG', name: 'Antigua and Barbuda', nameFr: 'Antigua-et-Barbuda' },
  { code: 'AR', name: 'Argentina', nameFr: 'Argentine' },
  { code: 'AM', name: 'Armenia', nameFr: 'Arménie' },
  { code: 'AU', name: 'Australia', nameFr: 'Australie' },
  { code: 'AT', name: 'Austria', nameFr: 'Autriche' },
  { code: 'AZ', name: 'Azerbaijan', nameFr: 'Azerbaïdjan' },
  { code: 'BS', name: 'Bahamas', nameFr: 'Bahamas' },
  { code: 'BH', name: 'Bahrain', nameFr: 'Bahreïn' },
  { code: 'BD', name: 'Bangladesh', nameFr: 'Bangladesh' },
  { code: 'BB', name: 'Barbados', nameFr: 'Barbade' },
  { code: 'BY', name: 'Belarus', nameFr: 'Biélorussie' },
  { code: 'BE', name: 'Belgium', nameFr: 'Belgique' },
  { code: 'BZ', name: 'Belize', nameFr: 'Belize' },
  { code: 'BJ', name: 'Benin', nameFr: 'Bénin' },
  { code: 'BT', name: 'Bhutan', nameFr: 'Bhoutan' },
  { code: 'BO', name: 'Bolivia', nameFr: 'Bolivie' },
  { code: 'BA', name: 'Bosnia and Herzegovina', nameFr: 'Bosnie-Herzégovine' },
  { code: 'BW', name: 'Botswana', nameFr: 'Botswana' },
  { code: 'BR', name: 'Brazil', nameFr: 'Brésil' },
  { code: 'BN', name: 'Brunei', nameFr: 'Brunei' },
  { code: 'BG', name: 'Bulgaria', nameFr: 'Bulgarie' },
  { code: 'BF', name: 'Burkina Faso', nameFr: 'Burkina Faso' },
  { code: 'BI', name: 'Burundi', nameFr: 'Burundi' },
  { code: 'CV', name: 'Cabo Verde', nameFr: 'Cap-Vert' },
  { code: 'KH', name: 'Cambodia', nameFr: 'Cambodge' },
  { code: 'CM', name: 'Cameroon', nameFr: 'Cameroun' },
  { code: 'CA', name: 'Canada', nameFr: 'Canada' },
  { code: 'CF', name: 'Central African Republic', nameFr: 'République centrafricaine' },
  { code: 'TD', name: 'Chad', nameFr: 'Tchad' },
  { code: 'CL', name: 'Chile', nameFr: 'Chili' },
  { code: 'CN', name: 'China', nameFr: 'Chine' },
  { code: 'CO', name: 'Colombia', nameFr: 'Colombie' },
  { code: 'KM', name: 'Comoros', nameFr: 'Comores' },
  { code: 'CG', name: 'Congo', nameFr: 'Congo' },
  { code: 'CD', name: 'Congo (DRC)', nameFr: 'RD Congo' },
  { code: 'CR', name: 'Costa Rica', nameFr: 'Costa Rica' },
  { code: 'CI', name: 'Côte d\'Ivoire', nameFr: 'Côte d\'Ivoire' },
  { code: 'HR', name: 'Croatia', nameFr: 'Croatie' },
  { code: 'CU', name: 'Cuba', nameFr: 'Cuba' },
  { code: 'CY', name: 'Cyprus', nameFr: 'Chypre' },
  { code: 'CZ', name: 'Czechia', nameFr: 'Tchéquie' },
  { code: 'DK', name: 'Denmark', nameFr: 'Danemark' },
  { code: 'DJ', name: 'Djibouti', nameFr: 'Djibouti' },
  { code: 'DM', name: 'Dominica', nameFr: 'Dominique' },
  { code: 'DO', name: 'Dominican Republic', nameFr: 'République dominicaine' },
  { code: 'EC', name: 'Ecuador', nameFr: 'Équateur' },
  { code: 'EG', name: 'Egypt', nameFr: 'Égypte' },
  { code: 'SV', name: 'El Salvador', nameFr: 'Salvador' },
  { code: 'GQ', name: 'Equatorial Guinea', nameFr: 'Guinée équatoriale' },
  { code: 'ER', name: 'Eritrea', nameFr: 'Érythrée' },
  { code: 'EE', name: 'Estonia', nameFr: 'Estonie' },
  { code: 'SZ', name: 'Eswatini', nameFr: 'Eswatini' },
  { code: 'ET', name: 'Ethiopia', nameFr: 'Éthiopie' },
  { code: 'FJ', name: 'Fiji', nameFr: 'Fidji' },
  { code: 'FI', name: 'Finland', nameFr: 'Finlande' },
  { code: 'FR', name: 'France', nameFr: 'France' },
  { code: 'GA', name: 'Gabon', nameFr: 'Gabon' },
  { code: 'GM', name: 'Gambia', nameFr: 'Gambie' },
  { code: 'GE', name: 'Georgia', nameFr: 'Géorgie' },
  { code: 'DE', name: 'Germany', nameFr: 'Allemagne' },
  { code: 'GH', name: 'Ghana', nameFr: 'Ghana' },
  { code: 'GR', name: 'Greece', nameFr: 'Grèce' },
  { code: 'GD', name: 'Grenada', nameFr: 'Grenade' },
  { code: 'GT', name: 'Guatemala', nameFr: 'Guatemala' },
  { code: 'GN', name: 'Guinea', nameFr: 'Guinée' },
  { code: 'GW', name: 'Guinea-Bissau', nameFr: 'Guinée-Bissau' },
  { code: 'GY', name: 'Guyana', nameFr: 'Guyana' },
  { code: 'HT', name: 'Haiti', nameFr: 'Haïti' },
  { code: 'HN', name: 'Honduras', nameFr: 'Honduras' },
  { code: 'HU', name: 'Hungary', nameFr: 'Hongrie' },
  { code: 'IS', name: 'Iceland', nameFr: 'Islande' },
  { code: 'IN', name: 'India', nameFr: 'Inde' },
  { code: 'ID', name: 'Indonesia', nameFr: 'Indonésie' },
  { code: 'IR', name: 'Iran', nameFr: 'Iran' },
  { code: 'IQ', name: 'Iraq', nameFr: 'Irak' },
  { code: 'IE', name: 'Ireland', nameFr: 'Irlande' },
  { code: 'IL', name: 'Israel', nameFr: 'Israël' },
  { code: 'IT', name: 'Italy', nameFr: 'Italie' },
  { code: 'JM', name: 'Jamaica', nameFr: 'Jamaïque' },
  { code: 'JP', name: 'Japan', nameFr: 'Japon' },
  { code: 'JO', name: 'Jordan', nameFr: 'Jordanie' },
  { code: 'KZ', name: 'Kazakhstan', nameFr: 'Kazakhstan' },
  { code: 'KE', name: 'Kenya', nameFr: 'Kenya' },
  { code: 'KI', name: 'Kiribati', nameFr: 'Kiribati' },
  { code: 'KP', name: 'North Korea', nameFr: 'Corée du Nord' },
  { code: 'KR', name: 'South Korea', nameFr: 'Corée du Sud' },
  { code: 'KW', name: 'Kuwait', nameFr: 'Koweït' },
  { code: 'KG', name: 'Kyrgyzstan', nameFr: 'Kirghizistan' },
  { code: 'LA', name: 'Laos', nameFr: 'Laos' },
  { code: 'LV', name: 'Latvia', nameFr: 'Lettonie' },
  { code: 'LB', name: 'Lebanon', nameFr: 'Liban' },
  { code: 'LS', name: 'Lesotho', nameFr: 'Lesotho' },
  { code: 'LR', name: 'Liberia', nameFr: 'Liberia' },
  { code: 'LY', name: 'Libya', nameFr: 'Libye' },
  { code: 'LI', name: 'Liechtenstein', nameFr: 'Liechtenstein' },
  { code: 'LT', name: 'Lithuania', nameFr: 'Lituanie' },
  { code: 'LU', name: 'Luxembourg', nameFr: 'Luxembourg' },
  { code: 'MG', name: 'Madagascar', nameFr: 'Madagascar' },
  { code: 'MW', name: 'Malawi', nameFr: 'Malawi' },
  { code: 'MY', name: 'Malaysia', nameFr: 'Malaisie' },
  { code: 'MV', name: 'Maldives', nameFr: 'Maldives' },
  { code: 'ML', name: 'Mali', nameFr: 'Mali' },
  { code: 'MT', name: 'Malta', nameFr: 'Malte' },
  { code: 'MH', name: 'Marshall Islands', nameFr: 'Îles Marshall' },
  { code: 'MR', name: 'Mauritania', nameFr: 'Mauritanie' },
  { code: 'MU', name: 'Mauritius', nameFr: 'Maurice' },
  { code: 'MX', name: 'Mexico', nameFr: 'Mexique' },
  { code: 'FM', name: 'Micronesia', nameFr: 'Micronésie' },
  { code: 'MD', name: 'Moldova', nameFr: 'Moldavie' },
  { code: 'MC', name: 'Monaco', nameFr: 'Monaco' },
  { code: 'MN', name: 'Mongolia', nameFr: 'Mongolie' },
  { code: 'ME', name: 'Montenegro', nameFr: 'Monténégro' },
  { code: 'MA', name: 'Morocco', nameFr: 'Maroc' },
  { code: 'MZ', name: 'Mozambique', nameFr: 'Mozambique' },
  { code: 'MM', name: 'Myanmar', nameFr: 'Myanmar' },
  { code: 'NA', name: 'Namibia', nameFr: 'Namibie' },
  { code: 'NR', name: 'Nauru', nameFr: 'Nauru' },
  { code: 'NP', name: 'Nepal', nameFr: 'Népal' },
  { code: 'NL', name: 'Netherlands', nameFr: 'Pays-Bas' },
  { code: 'NZ', name: 'New Zealand', nameFr: 'Nouvelle-Zélande' },
  { code: 'NI', name: 'Nicaragua', nameFr: 'Nicaragua' },
  { code: 'NE', name: 'Niger', nameFr: 'Niger' },
  { code: 'NG', name: 'Nigeria', nameFr: 'Nigeria' },
  { code: 'MK', name: 'North Macedonia', nameFr: 'Macédoine du Nord' },
  { code: 'NO', name: 'Norway', nameFr: 'Norvège' },
  { code: 'OM', name: 'Oman', nameFr: 'Oman' },
  { code: 'PK', name: 'Pakistan', nameFr: 'Pakistan' },
  { code: 'PW', name: 'Palau', nameFr: 'Palaos' },
  { code: 'PS', name: 'Palestine', nameFr: 'Palestine' },
  { code: 'PA', name: 'Panama', nameFr: 'Panama' },
  { code: 'PG', name: 'Papua New Guinea', nameFr: 'Papouasie-Nouvelle-Guinée' },
  { code: 'PY', name: 'Paraguay', nameFr: 'Paraguay' },
  { code: 'PE', name: 'Peru', nameFr: 'Pérou' },
  { code: 'PH', name: 'Philippines', nameFr: 'Philippines' },
  { code: 'PL', name: 'Poland', nameFr: 'Pologne' },
  { code: 'PT', name: 'Portugal', nameFr: 'Portugal' },
  { code: 'QA', name: 'Qatar', nameFr: 'Qatar' },
  { code: 'RO', name: 'Romania', nameFr: 'Roumanie' },
  { code: 'RU', name: 'Russia', nameFr: 'Russie' },
  { code: 'RW', name: 'Rwanda', nameFr: 'Rwanda' },
  { code: 'KN', name: 'Saint Kitts and Nevis', nameFr: 'Saint-Kitts-et-Nevis' },
  { code: 'LC', name: 'Saint Lucia', nameFr: 'Sainte-Lucie' },
  { code: 'VC', name: 'Saint Vincent and the Grenadines', nameFr: 'Saint-Vincent-et-les-Grenadines' },
  { code: 'WS', name: 'Samoa', nameFr: 'Samoa' },
  { code: 'SM', name: 'San Marino', nameFr: 'Saint-Marin' },
  { code: 'ST', name: 'São Tomé and Príncipe', nameFr: 'Sao Tomé-et-Príncipe' },
  { code: 'SA', name: 'Saudi Arabia', nameFr: 'Arabie saoudite' },
  { code: 'SN', name: 'Senegal', nameFr: 'Sénégal' },
  { code: 'RS', name: 'Serbia', nameFr: 'Serbie' },
  { code: 'SC', name: 'Seychelles', nameFr: 'Seychelles' },
  { code: 'SL', name: 'Sierra Leone', nameFr: 'Sierra Leone' },
  { code: 'SG', name: 'Singapore', nameFr: 'Singapour' },
  { code: 'SK', name: 'Slovakia', nameFr: 'Slovaquie' },
  { code: 'SI', name: 'Slovenia', nameFr: 'Slovénie' },
  { code: 'SB', name: 'Solomon Islands', nameFr: 'Îles Salomon' },
  { code: 'SO', name: 'Somalia', nameFr: 'Somalie' },
  { code: 'ZA', name: 'South Africa', nameFr: 'Afrique du Sud' },
  { code: 'SS', name: 'South Sudan', nameFr: 'Soudan du Sud' },
  { code: 'ES', name: 'Spain', nameFr: 'Espagne' },
  { code: 'LK', name: 'Sri Lanka', nameFr: 'Sri Lanka' },
  { code: 'SD', name: 'Sudan', nameFr: 'Soudan' },
  { code: 'SR', name: 'Suriname', nameFr: 'Suriname' },
  { code: 'SE', name: 'Sweden', nameFr: 'Suède' },
  { code: 'CH', name: 'Switzerland', nameFr: 'Suisse' },
  { code: 'SY', name: 'Syria', nameFr: 'Syrie' },
  { code: 'TW', name: 'Taiwan', nameFr: 'Taïwan' },
  { code: 'TJ', name: 'Tajikistan', nameFr: 'Tadjikistan' },
  { code: 'TZ', name: 'Tanzania', nameFr: 'Tanzanie' },
  { code: 'TH', name: 'Thailand', nameFr: 'Thaïlande' },
  { code: 'TL', name: 'Timor-Leste', nameFr: 'Timor oriental' },
  { code: 'TG', name: 'Togo', nameFr: 'Togo' },
  { code: 'TO', name: 'Tonga', nameFr: 'Tonga' },
  { code: 'TT', name: 'Trinidad and Tobago', nameFr: 'Trinité-et-Tobago' },
  { code: 'TN', name: 'Tunisia', nameFr: 'Tunisie' },
  { code: 'TR', name: 'Turkey', nameFr: 'Turquie' },
  { code: 'TM', name: 'Turkmenistan', nameFr: 'Turkménistan' },
  { code: 'TV', name: 'Tuvalu', nameFr: 'Tuvalu' },
  { code: 'UG', name: 'Uganda', nameFr: 'Ouganda' },
  { code: 'UA', name: 'Ukraine', nameFr: 'Ukraine' },
  { code: 'AE', name: 'United Arab Emirates', nameFr: 'Émirats arabes unis' },
  { code: 'GB', name: 'United Kingdom', nameFr: 'Royaume-Uni' },
  { code: 'US', name: 'United States', nameFr: 'États-Unis' },
  { code: 'UY', name: 'Uruguay', nameFr: 'Uruguay' },
  { code: 'UZ', name: 'Uzbekistan', nameFr: 'Ouzbékistan' },
  { code: 'VU', name: 'Vanuatu', nameFr: 'Vanuatu' },
  { code: 'VA', name: 'Vatican City', nameFr: 'Vatican' },
  { code: 'VE', name: 'Venezuela', nameFr: 'Venezuela' },
  { code: 'VN', name: 'Vietnam', nameFr: 'Vietnam' },
  { code: 'YE', name: 'Yemen', nameFr: 'Yémen' },
  { code: 'ZM', name: 'Zambia', nameFr: 'Zambie' },
  { code: 'ZW', name: 'Zimbabwe', nameFr: 'Zimbabwe' },
];

/** Get country name by code */
export function getCountryName(code: string, locale: string = 'en'): string {
  const c = COUNTRIES.find(c => c.code === code.toUpperCase());
  if (!c) return code;
  return locale === 'fr' ? c.nameFr : c.name;
}
