import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

/**
 * INSPIRATION DIGEST — AI-generated marketing/inspiration emails
 * Triggered Mon/Tue/Thu via pg_cron, sent to all 4 segments.
 *
 * Content is generated by Lovable AI (Gemini) and includes:
 *  - Success stories (with realistic but elevated numbers)
 *  - Tips & best practices
 *  - Product news / new features
 *  - Inspirational case studies
 *
 * IMPORTANT: We use plausible elevated numbers (not real DB metrics)
 * because the platform is still young. The AI is instructed to stay
 * within realistic ranges and to vary content each run.
 */

type Segment = 'all_active' | 'creators' | 'ambassadors' | 'buyers';
type Lang = 'fr' | 'en';

const THEMES = [
  'success_story',           // "Comment X a fait Y FCFA en 30 jours"
  'tips_marketing',          // "5 astuces pour vendre sur WhatsApp"
  'new_feature',             // "Nouveau : générateur de livre IA en 2 min"
  'case_study',              // "Étude de cas : ROI 320% avec ces 3 leviers"
  'monetization_advice',     // "Le secret des créateurs qui gagnent 500k/mois"
  'ambassador_motivation',   // "Comment 1 partage WhatsApp = 25 000 FCFA"
  'creator_growth',          // "De 0 à 100 ventes en 14 jours"
];

function pickTheme(seed: number): string {
  return THEMES[seed % THEMES.length];
}

function dayKey(): string {
  return new Date().toISOString().slice(0, 10); // YYYY-MM-DD
}

async function generateContent(
  apiKey: string,
  segment: Segment,
  lang: Lang,
  theme: string,
): Promise<{ subject_line: string; headline: string; body_html: string; cta_text: string; cta_url: string } | null> {
  const segmentDescriptions: Record<Segment, { fr: string; en: string }> = {
    all_active: {
      fr: 'utilisateurs actifs de SiteViral (acheteurs, créateurs, visiteurs récents)',
      en: 'active SiteViral users (buyers, creators, recent visitors)',
    },
    creators: {
      fr: 'créateurs et administrateurs d\'organisations qui vendent ou collectent des dons',
      en: 'creators and organization admins who sell or collect donations',
    },
    ambassadors: {
      fr: 'ambassadeurs qui promeuvent les produits et gagnent des commissions',
      en: 'ambassadors who promote products and earn commissions',
    },
    buyers: {
      fr: 'acheteurs qui ont déjà acheté au moins un produit ou fait un don',
      en: 'buyers who have already purchased at least one product or made a donation',
    },
  };

  const ctaBySegment: Record<Segment, { fr: { text: string; url: string }; en: { text: string; url: string } }> = {
    all_active: {
      fr: { text: 'Explorer SiteViral →', url: 'https://siteviral.com/feed' },
      en: { text: 'Explore SiteViral →', url: 'https://siteviral.com/feed' },
    },
    creators: {
      fr: { text: 'Aller à mon dashboard →', url: 'https://siteviral.com/admin' },
      en: { text: 'Go to my dashboard →', url: 'https://siteviral.com/admin' },
    },
    ambassadors: {
      fr: { text: 'Voir mes liens ambassadeur →', url: 'https://siteviral.com/gagner' },
      en: { text: 'View my ambassador links →', url: 'https://siteviral.com/gagner' },
    },
    buyers: {
      fr: { text: 'Créer mon premier produit IA →', url: 'https://siteviral.com/ecrire' },
      en: { text: 'Create my first AI product →', url: 'https://siteviral.com/ecrire' },
    },
  };

  const isFr = lang === 'fr';
  const langName = isFr ? 'French (français)' : 'English';
  const seg = segmentDescriptions[segment][lang];

  const systemPrompt = `You are a senior copywriter for SiteViral — an African creator/commerce platform similar to Gumroad+Patreon (digital products, donations, ambassador program with 10% commissions, AI Studio for ebooks/courses).

Write a SHORT inspirational/marketing email in ${langName}, similar in style to Microsoft Ads' "How brand X succeeded" emails. The tone is: warm, concrete, success-focused, lightly aspirational. Currency: FCFA (XOF) for FR, USD ($) for EN.

CRITICAL RULES:
- Use REALISTIC but ELEVATED numbers (e.g. "234% growth", "150 000 FCFA in 30 days", "5x ROI"). These are illustrative — do NOT cite real SiteViral data.
- Numbers should sound credible (not "1 million FCFA in 1 day").
- Tell a specific story or share a specific tip — never generic.
- Mention specific SiteViral features when relevant (AI Studio, Ambassador Program, donations, etc.).
- NO emojis in the headline. Max 2 emojis in body.
- Body HTML uses simple tags only: <p>, <strong>, <em>, <ul>, <li>, <br>. No inline styles, no <h1>/<h2>/<div>.
- Body length: 80-140 words.

Return ONLY a valid JSON object with these exact keys:
{
  "subject_line": "string, max 60 chars, no emoji prefix",
  "headline": "string, max 70 chars, plain text",
  "body_html": "string, simple HTML body (80-140 words)"
}`;

  const userPrompt = `Audience: ${seg}
Theme: ${theme}
Language: ${langName}

Write a fresh, varied email about this theme for this audience. Make the story or tip CONCRETE and SPECIFIC.`;

  try {
    const res = await fetch('https://ai.gateway.lovable.dev/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${apiKey}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: 'google/gemini-2.5-flash',
        messages: [
          { role: 'system', content: systemPrompt },
          { role: 'user', content: userPrompt },
        ],
        response_format: { type: 'json_object' },
      }),
    });

    if (!res.ok) {
      console.error(`[inspiration] AI gateway ${res.status}:`, await res.text());
      return null;
    }

    const json = await res.json();
    const content = json.choices?.[0]?.message?.content;
    if (!content) return null;

    const parsed = JSON.parse(content);
    if (!parsed.subject_line || !parsed.headline || !parsed.body_html) return null;

    const cta = ctaBySegment[segment][lang];
    return {
      subject_line: String(parsed.subject_line).slice(0, 80),
      headline: String(parsed.headline).slice(0, 90),
      body_html: String(parsed.body_html),
      cta_text: cta.text,
      cta_url: cta.url,
    };
  } catch (err) {
    console.error('[inspiration] AI generation error:', err);
    return null;
  }
}

async function getRecipients(db: any, segment: Segment): Promise<Array<{ email: string; name: string | null; lang: Lang }>> {
  // Last 90 days = "active". For ambassadors/creators we don't filter by date as strictly.
  const ninetyDaysAgo = new Date(Date.now() - 90 * 86400000).toISOString();
  const recipients: Array<{ email: string; name: string | null; lang: Lang }> = [];
  const seen = new Set<string>();

  // Helper to fetch emails for a list of user_ids
  async function emailsForUsers(userIds: string[]): Promise<Array<{ email: string; name: string | null; lang: Lang }>> {
    const out: Array<{ email: string; name: string | null; lang: Lang }> = [];
    for (let i = 0; i < userIds.length; i += 100) {
      const batch = userIds.slice(i, i + 100);
      const { data: profiles } = await db.from('profiles')
        .select('id, display_name, language, email_marketing_opted_out')
        .in('id', batch);
      for (const p of profiles || []) {
        if (p.email_marketing_opted_out) continue;
        try {
          const { data } = await db.auth.admin.getUserById(p.id);
          const email = data?.user?.email;
          if (email && !seen.has(email)) {
            seen.add(email);
            out.push({
              email,
              name: p.display_name,
              lang: (p.language === 'en' ? 'en' : 'fr') as Lang,
            });
          }
        } catch {}
      }
    }
    return out;
  }

  if (segment === 'all_active') {
    const { data: actives } = await db.from('profiles')
      .select('id')
      .gte('updated_at', ninetyDaysAgo)
      .eq('email_marketing_opted_out', false)
      .limit(2000);
    const ids = (actives || []).map((r: any) => r.id);
    return emailsForUsers(ids);
  }

  if (segment === 'creators') {
    const { data: roles } = await db.from('user_organization_roles')
      .select('user_id')
      .in('role', ['admin', 'owner', 'editor'])
      .limit(2000);
    const ids = Array.from(new Set((roles || []).map((r: any) => r.user_id)));
    return emailsForUsers(ids);
  }

  if (segment === 'ambassadors') {
    const { data: links } = await db.from('affiliate_links')
      .select('user_id').eq('is_active', true).limit(2000);
    const ids = Array.from(new Set((links || []).map((r: any) => r.user_id)));
    return emailsForUsers(ids);
  }

  if (segment === 'buyers') {
    const { data: purchases } = await db.from('product_purchases')
      .select('user_id').eq('status', 'completed').limit(2000);
    const ids = Array.from(new Set((purchases || []).map((r: any) => r.user_id).filter(Boolean)));
    return emailsForUsers(ids);
  }

  return recipients;
}

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') return new Response(null, { headers: corsHeaders });

  const SUPABASE_URL = Deno.env.get('SUPABASE_URL')!;
  const SERVICE_KEY = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
  const RESEND_API_KEY = Deno.env.get('RESEND_API_KEY');
  const LOVABLE_API_KEY = Deno.env.get('LOVABLE_API_KEY');
  const db = createClient(SUPABASE_URL, SERVICE_KEY);

  if (!RESEND_API_KEY || !LOVABLE_API_KEY) {
    return new Response(JSON.stringify({ error: 'Missing RESEND_API_KEY or LOVABLE_API_KEY' }), {
      status: 500,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }

  // Optional body to force segment / theme (for manual tests / preview)
  let forced: { segment?: Segment; theme?: string; preview_only?: boolean } = {};
  try {
    if (req.method === 'POST' && req.headers.get('content-type')?.includes('application/json')) {
      forced = await req.json().catch(() => ({}));
    }
  } catch {}

  const segments: Segment[] = forced.segment ? [forced.segment] : ['all_active', 'creators', 'ambassadors', 'buyers'];
  const day = dayKey();
  const seed = parseInt(day.replace(/-/g, ''), 10);
  const baseTheme = forced.theme || pickTheme(seed);

  const summary: Record<string, { generated: boolean; recipients: number; sent: number }> = {};

  for (let segIdx = 0; segIdx < segments.length; segIdx++) {
    const segment = segments[segIdx];
    // Vary theme per segment so each batch is unique
    const theme = forced.theme || pickTheme(seed + segIdx);

    // Generate FR + EN versions in parallel
    const [contentFr, contentEn] = await Promise.all([
      generateContent(LOVABLE_API_KEY, segment, 'fr', theme),
      generateContent(LOVABLE_API_KEY, segment, 'en', theme),
    ]);

    if (!contentFr || !contentEn) {
      summary[segment] = { generated: false, recipients: 0, sent: 0 };
      console.error(`[inspiration] Skipping ${segment}: AI generation failed`);
      continue;
    }

    if (forced.preview_only) {
      summary[segment] = { generated: true, recipients: 0, sent: 0 };
      // Return previews
      return new Response(JSON.stringify({ ok: true, preview: { fr: contentFr, en: contentEn }, theme, segment }), {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    // Fetch recipients for this segment
    const recipients = await getRecipients(db, segment);
    summary[segment] = { generated: true, recipients: recipients.length, sent: 0 };

    if (!recipients.length) continue;

    // Send via Resend in batches of 50, respecting rate limits (1.5s between batches)
    let sentCount = 0;
    const batchSize = 50;

    for (let i = 0; i < recipients.length; i += batchSize) {
      const batch = recipients.slice(i, i + batchSize);
      const emailsPayload = batch.map(r => {
        const c = r.lang === 'en' ? contentEn : contentFr;
        return {
          from: 'SiteViral Inspiration <inspiration@siteviral.com>',
          to: r.email,
          subject: c.subject_line,
          html: `<!DOCTYPE html><html lang="${r.lang}"><body style="font-family:sans-serif;background:#0f0f0f;color:#eee;padding:32px;margin:0">
            <div style="max-width:560px;margin:0 auto;background:#1a1a1a;border-radius:16px;padding:32px;border:1px solid #333">
              <p style="font-size:11px;letter-spacing:1px;text-transform:uppercase;color:#1a66e6;margin:0 0 8px">${r.lang === 'en' ? 'Inspiration' : 'Inspiration'}</p>
              <h1 style="color:#fff;margin:0 0 20px;font-size:22px;line-height:1.3">${c.headline}</h1>
              <div style="color:#ddd;line-height:1.6;font-size:14px">${c.body_html}</div>
              <p style="margin:24px 0"><a href="${c.cta_url}" style="display:inline-block;background:#1a66e6;color:#fff;padding:12px 24px;border-radius:8px;font-weight:bold;text-decoration:none">${c.cta_text}</a></p>
              <p style="font-size:13px;color:#999;margin-top:24px">${r.lang === 'en' ? 'Talk soon,' : 'À très vite,'}<br/><strong style="color:#ccc">${r.lang === 'en' ? 'The SiteViral team' : 'L\'équipe SiteViral'}</strong></p>
              <div style="margin-top:32px;padding-top:16px;border-top:1px solid #333;font-size:11px;color:#777">
                <p>SiteViral — Operated by Hacktualiz Inc.</p>
                <p>131 Continental Dr, Suite 305, Newark, DE 19713, USA</p>
                <p><a href="https://siteviral.com/email-preferences?email=${encodeURIComponent(r.email)}" style="color:#1a66e6">${r.lang === 'en' ? 'Unsubscribe' : 'Se désabonner'}</a> · <a href="https://siteviral.com/privacy" style="color:#1a66e6">${r.lang === 'en' ? 'Privacy' : 'Confidentialité'}</a></p>
              </div>
            </div></body></html>`,
        };
      });

      try {
        const res = await fetch('https://api.resend.com/emails/batch', {
          method: 'POST',
          headers: { Authorization: `Bearer ${RESEND_API_KEY}`, 'Content-Type': 'application/json' },
          body: JSON.stringify(emailsPayload),
        });
        if (res.ok) {
          sentCount += batch.length;
        } else if (res.status === 429) {
          // Rate-limited: wait 3s and retry once
          await new Promise(r => setTimeout(r, 3000));
          const retry = await fetch('https://api.resend.com/emails/batch', {
            method: 'POST',
            headers: { Authorization: `Bearer ${RESEND_API_KEY}`, 'Content-Type': 'application/json' },
            body: JSON.stringify(emailsPayload),
          });
          if (retry.ok) sentCount += batch.length;
          else console.error(`[inspiration] retry failed:`, await retry.text());
        } else {
          console.error(`[inspiration] batch failed ${res.status}:`, await res.text());
        }
      } catch (err) {
        console.error('[inspiration] batch send error:', err);
      }

      // Throttle between batches (Resend: 2 req/s limit)
      if (i + batchSize < recipients.length) {
        await new Promise(r => setTimeout(r, 1500));
      }
    }

    summary[segment].sent = sentCount;

    // Log to email_logs (one row per segment send for traceability)
    try {
      await db.from('email_logs').insert({
        recipient: `[${segment}] ${recipients.length} recipients`,
        template: 'inspiration_digest',
        subject: contentFr.subject_line,
        status: sentCount > 0 ? 'sent' : 'failed',
        metadata: { segment, theme, sent: sentCount, total: recipients.length, day },
      });
    } catch {}
  }

  return new Response(JSON.stringify({ ok: true, day, theme: baseTheme, summary }), {
    headers: { ...corsHeaders, 'Content-Type': 'application/json' },
  });
});
