import LegalPageShell, { proseClasses } from '@/components/layout/LegalPageShell';
import { SEOHead } from '@/components/seo/SEOHead';
import { useI18n } from '@/i18n/I18nContext';

export default function PartnerTermsPage() {
  const { locale } = useI18n();
  const isFr = locale === 'fr';

  return (
    <LegalPageShell>
      <SEOHead
        title={isFr ? 'Contrat de Partenariat – Siteviral' : 'Partner Agreement – Siteviral'}
        description={isFr ? 'Conditions du Programme Partenaires Officiel Siteviral.' : 'Terms of the Official Siteviral Partner Program.'}
      />

      <h1 className="text-3xl sm:text-4xl font-extrabold mb-2">
        {isFr ? 'Contrat de Partenariat' : 'Partner Agreement'}
      </h1>
      <p className="text-sm text-muted-foreground mb-8">
        {isFr ? 'Dernière mise à jour : 25 février 2026' : 'Last updated: February 25, 2026'}
      </p>

      <div className={proseClasses}>
        <p>
          {isFr
            ? 'Le présent contrat (« Contrat ») est conclu entre Hacktualiz Inc., société C-Corp enregistrée au Delaware, États-Unis (« Siteviral », « la Plateforme », « nous ») et toute personne physique ou morale acceptant les termes ci-dessous (« le Partenaire », « vous »).'
            : 'This agreement ("Agreement") is entered into between Hacktualiz Inc., a C-Corp registered in Delaware, United States ("Siteviral", "the Platform", "we") and any individual or entity accepting the terms below ("the Partner", "you").'}
        </p>

        <h2>{isFr ? '1. Objet' : '1. Purpose'}</h2>
        <p>
          {isFr
            ? 'Le Programme Partenaires permet au Partenaire de référer des organisations tierces à la Plateforme en échange de commissions récurrentes calculées sur les frais de plateforme générés par ces organisations.'
            : 'The Partner Program allows the Partner to refer third-party organizations to the Platform in exchange for recurring commissions calculated on the platform fees generated by those organizations.'}
        </p>

        <h2>{isFr ? "2. Conditions d'éligibilité" : '2. Eligibility Conditions'}</h2>
        <ul className="list-disc pl-6 space-y-1">
          <li>{isFr ? "Être âgé d'au moins 18 ans." : 'Be at least 18 years old.'}</li>
          <li>{isFr ? "Fournir des informations exactes lors de l'inscription." : 'Provide accurate information during registration.'}</li>
          <li>{isFr ? "Compléter la vérification d'identité (KYC) avant le premier paiement." : 'Complete identity verification (KYC) before first payment.'}</li>
          <li>{isFr ? 'Ne pas être propriétaire ni administrateur des organisations référées.' : 'Not be the owner or administrator of referred organizations.'}</li>
          <li>{isFr ? "Respecter les Conditions Générales et la Politique d'Utilisation Acceptable de Siteviral." : "Comply with Siteviral's Terms of Service and Acceptable Use Policy."}</li>
        </ul>

        <h2>{isFr ? '3. Fonctionnement' : '3. How It Works'}</h2>
        <p>
          <strong>{isFr ? "3.1 Code d'invitation." : '3.1 Invitation Code.'}</strong> {isFr
            ? "Chaque Partenaire approuvé reçoit un code d'invitation unique. Lorsqu'une organisation est créée en utilisant ce code, elle est automatiquement attribuée au Partenaire."
            : 'Each approved Partner receives a unique invitation code. When an organization is created using this code, it is automatically attributed to the Partner.'}
        </p>
        <p>
          <strong>3.2 Attribution.</strong> {isFr
            ? "L'attribution est permanente et exclusive : une organisation ne peut être attribuée qu'à un seul Partenaire. Les auto-référencements sont détectés et interdits."
            : 'Attribution is permanent and exclusive: an organization can only be attributed to a single Partner. Self-referrals are detected and prohibited.'}
        </p>
        <p>
          <strong>3.3 Activation.</strong> {isFr
            ? 'Une organisation référée devient « active » lorsqu\'elle réalise sa première transaction monétisée sur la Plateforme.'
            : 'A referred organization becomes "active" when it completes its first monetized transaction on the Platform.'}
        </p>

        <h2>{isFr ? '4. Rémunération' : '4. Compensation'}</h2>
        <p>
          <strong>{isFr ? '4.1 Base de calcul.' : '4.1 Calculation Basis.'}</strong> {isFr
            ? 'Les commissions sont calculées exclusivement sur la part des frais de plateforme (platform fee) collectés sur chaque transaction monétisée. Les donations pures ne génèrent pas de commission partenaire.'
            : 'Commissions are calculated exclusively on the platform fee portion collected on each monetized transaction. Pure donations do not generate partner commissions.'}
        </p>
        <p>
          <strong>{isFr ? '4.2 Taux de commission.' : '4.2 Commission Rate.'}</strong> {isFr ? 'Le taux varie selon le niveau du Partenaire :' : 'The rate varies by Partner level:'}
        </p>
        <ul className="list-disc pl-6 space-y-1">
          <li><strong>Bronze</strong> (10+ {isFr ? 'orgs actives' : 'active orgs'}) : 5%</li>
          <li><strong>{isFr ? 'Argent' : 'Silver'}</strong> (50+) : 8%</li>
          <li><strong>{isFr ? 'Or' : 'Gold'}</strong> (150+) : 10%</li>
          <li><strong>{isFr ? 'Platine' : 'Platinum'}</strong> (300+) : 12%</li>
          <li><strong>{isFr ? 'Diamant' : 'Diamond'}</strong> (1 000+) : 15%</li>
        </ul>
        <p>{isFr ? "Siteviral se réserve le droit d'accorder un taux personnalisé à tout Partenaire." : 'Siteviral reserves the right to grant a customized rate to any Partner.'}</p>

        <p>
          <strong>{isFr ? '4.3 Période de rétention.' : '4.3 Holding Period.'}</strong> {isFr
            ? 'Chaque commission est retenue pendant 15 jours calendaires après la transaction pour couvrir les éventuels remboursements ou litiges. Après cette période, la commission devient « payable ».'
            : 'Each commission is held for 15 calendar days after the transaction to cover potential refunds or disputes. After this period, the commission becomes "payable".'}
        </p>
        <p>
          <strong>{isFr ? '4.4 Seuil minimum.' : '4.4 Minimum Threshold.'}</strong> {isFr
            ? 'Le seuil minimum de retrait est de 5 000 XOF (ou équivalent).'
            : 'The minimum withdrawal threshold is 5,000 XOF (or equivalent).'}
        </p>
        <p>
          <strong>{isFr ? '4.5 Méthodes de paiement.' : '4.5 Payment Methods.'}</strong> {isFr
            ? 'Les paiements sont effectués via virement bancaire ou Mobile Money (Orange Money, MTN Mobile Money, Moov Money) selon la disponibilité dans votre pays.'
            : 'Payments are made via bank transfer or Mobile Money (Orange Money, MTN Mobile Money, Moov Money) depending on availability in your country.'}
        </p>

        <h2>{isFr ? "5. Vérification d'identité (KYC)" : '5. Identity Verification (KYC)'}</h2>
        <p>
          {isFr
            ? "Avant tout premier paiement, le Partenaire doit compléter la vérification d'identité en fournissant une pièce d'identité valide (carte nationale d'identité, passeport ou permis de conduire). Les informations fournies sont traitées conformément à notre Politique de Confidentialité."
            : 'Before any first payment, the Partner must complete identity verification by providing a valid identity document (national ID card, passport, or driver\'s license). The information provided is processed in accordance with our Privacy Policy.'}
        </p>

        <h2>{isFr ? '6. Obligations du Partenaire' : '6. Partner Obligations'}</h2>
        <ul className="list-disc pl-6 space-y-1">
          <li>{isFr ? 'Ne pas utiliser de méthodes trompeuses, de spam ou de pratiques abusives pour recruter des organisations.' : 'Not use deceptive methods, spam, or abusive practices to recruit organizations.'}</li>
          <li>{isFr ? 'Ne pas créer de faux comptes ou d\'organisations fictives.' : 'Not create fake accounts or fictitious organizations.'}</li>
          <li>{isFr ? "Ne pas usurper l'identité de Siteviral ou prétendre être un employé." : 'Not impersonate Siteviral or claim to be an employee.'}</li>
          <li>{isFr ? 'Respecter toutes les lois applicables, y compris les réglementations anti-blanchiment (AML).' : 'Comply with all applicable laws, including anti-money laundering (AML) regulations.'}</li>
          <li>{isFr ? 'Informer immédiatement Siteviral de tout changement dans ses coordonnées bancaires.' : 'Immediately inform Siteviral of any changes in banking details.'}</li>
        </ul>

        <h2>{isFr ? '7. Suspension et résiliation' : '7. Suspension and Termination'}</h2>
        <p>
          <strong>7.1</strong> {isFr
            ? "Siteviral peut suspendre ou résilier le compte d'un Partenaire à tout moment en cas de violation du présent Contrat, d'activité frauduleuse, ou de non-respect des lois applicables."
            : "Siteviral may suspend or terminate a Partner's account at any time in case of violation of this Agreement, fraudulent activity, or non-compliance with applicable laws."}
        </p>
        <p>
          <strong>7.2</strong> {isFr
            ? 'En cas de résiliation, les commissions « payables » déjà acquises seront versées dans un délai de 30 jours. Les commissions « en attente » (held) seront annulées.'
            : 'Upon termination, "payable" commissions already earned will be paid within 30 days. "Held" commissions will be cancelled.'}
        </p>
        <p>
          <strong>7.3</strong> {isFr
            ? 'Le Partenaire peut résilier sa participation au programme à tout moment en contactant support@siteviral.com. Les commissions payables seront versées selon les conditions ci-dessus.'
            : 'The Partner may terminate their participation in the program at any time by contacting support@siteviral.com. Payable commissions will be paid according to the conditions above.'}
        </p>

        <h2>{isFr ? '8. Limitation de responsabilité' : '8. Limitation of Liability'}</h2>
        <p>
          {isFr
            ? "Siteviral ne garantit aucun niveau de revenu. Les commissions dépendent de l'activité commerciale des organisations référées. Siteviral ne sera pas responsable des pertes indirectes liées à la participation au Programme."
            : 'Siteviral does not guarantee any income level. Commissions depend on the commercial activity of referred organizations. Siteviral shall not be liable for indirect losses related to participation in the Program.'}
        </p>

        <h2>{isFr ? '9. Propriété intellectuelle' : '9. Intellectual Property'}</h2>
        <p>
          {isFr
            ? "Le Partenaire n'acquiert aucun droit sur les marques, logos ou contenus de Siteviral. L'utilisation de la marque Siteviral à des fins promotionnelles doit être préalablement autorisée par écrit."
            : "The Partner acquires no rights to Siteviral's trademarks, logos, or content. Use of the Siteviral brand for promotional purposes must be authorized in writing beforehand."}
        </p>

        <h2>{isFr ? '10. Confidentialité' : '10. Confidentiality'}</h2>
        <p>
          {isFr
            ? "Le Partenaire s'engage à ne pas divulguer les informations confidentielles auxquelles il pourrait avoir accès, notamment les données financières, les taux personnalisés ou les informations sur d'autres partenaires."
            : 'The Partner agrees not to disclose confidential information they may have access to, including financial data, customized rates, or information about other partners.'}
        </p>

        <h2>11. {isFr ? 'Modifications' : 'Changes'}</h2>
        <p>
          {isFr
            ? "Siteviral peut modifier le présent Contrat à tout moment. Les modifications entrent en vigueur 30 jours après notification par email. La poursuite de la participation au Programme après ce délai vaut acceptation."
            : 'Siteviral may modify this Agreement at any time. Changes take effect 30 days after email notification. Continued participation in the Program after this period constitutes acceptance.'}
        </p>

        <h2>{isFr ? '12. Droit applicable' : '12. Governing Law'}</h2>
        <p>
          {isFr
            ? "Le présent Contrat est régi par les lois de l'État du Delaware, États-Unis. Tout litige sera soumis à la juridiction exclusive des tribunaux du Delaware."
            : 'This Agreement is governed by the laws of the State of Delaware, United States. Any dispute shall be subject to the exclusive jurisdiction of Delaware courts.'}
        </p>

        <h2>13. Contact</h2>
        <p>
          {isFr ? 'Pour toute question relative au Programme Partenaires :' : 'For any questions about the Partner Program:'}<br />
          <strong>Email :</strong> partners@siteviral.com<br />
          <strong>{isFr ? 'Adresse :' : 'Address:'}</strong> Hacktualiz Inc., 131 Continental Dr, Suite 305, Newark, DE 19713, United States
        </p>
      </div>
    </LegalPageShell>
  );
}
