// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/who-am-i.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
var who_am_i_default = defineTool({
  name: "who_am_i",
  title: "Who am I",
  description: "Return the signed-in SiteViral user's id, email, and OAuth client id.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const info = {
      user_id: ctx.getUserId(),
      email: ctx.getUserEmail(),
      client_id: ctx.getClientId()
    };
    return {
      content: [{ type: "text", text: JSON.stringify(info, null, 2) }],
      structuredContent: info
    };
  }
});

// src/lib/mcp/tools/list-my-organizations.ts
import { createClient } from "npm:@supabase/supabase-js@^2.97.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
function db(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_my_organizations_default = defineTool2({
  name: "list_my_organizations",
  title: "List my organizations",
  description: "List SiteViral organizations the signed-in user belongs to, with their role.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supa = db(ctx);
    const { data, error } = await supa.from("organization_members").select("role, organizations(id, name, slug, description, created_at)").eq("user_id", ctx.getUserId());
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = (data ?? []).map((m) => ({
      id: m.organizations?.id,
      name: m.organizations?.name,
      slug: m.organizations?.slug,
      role: m.role,
      created_at: m.organizations?.created_at
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
      structuredContent: { organizations: rows }
    };
  }
});

// src/lib/mcp/tools/list-org-products.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.97.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
function db2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_org_products_default = defineTool3({
  name: "list_org_products",
  title: "List organization products",
  description: "List digital products for a SiteViral organization the user belongs to.",
  inputSchema: {
    organization_id: z.string().uuid().describe("Organization UUID"),
    limit: z.number().int().min(1).max(100).default(25)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ organization_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supa = db2(ctx);
    const { data, error } = await supa.from("digital_products").select("id, title, description, price, currency, is_free, status, created_at").eq("organization_id", organization_id).order("created_at", { ascending: false }).limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { products: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-my-purchases.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.97.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
function db3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_my_purchases_default = defineTool4({
  name: "list_my_purchases",
  title: "List my purchases",
  description: "List the signed-in user's SiteViral purchases (digital products, formations, credits, donations).",
  inputSchema: {
    limit: z2.number().int().min(1).max(100).default(25)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supa = db3(ctx);
    const { data, error } = await supa.from("purchases").select("id, product_id, amount, currency, status, created_at").eq("buyer_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { purchases: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-org-analytics.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.97.0";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^4.4.3";
function db4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_org_analytics_default = defineTool5({
  name: "get_org_analytics",
  title: "Get organization analytics",
  description: "Summary of an organization: total purchases, gross revenue, and recent order count over N days.",
  inputSchema: {
    organization_id: z3.string().uuid(),
    days: z3.number().int().min(1).max(365).default(30)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ organization_id, days }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supa = db4(ctx);
    const since = new Date(Date.now() - days * 864e5).toISOString();
    const { data, error } = await supa.from("purchases").select("amount, currency, status, created_at").eq("organization_id", organization_id).gte("created_at", since);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = data ?? [];
    const paid = rows.filter((r) => r.status === "paid" || r.status === "completed" || r.status === "success");
    const byCurrency = {};
    for (const r of paid) {
      const c = (r.currency ?? "XOF").toUpperCase();
      byCurrency[c] = (byCurrency[c] ?? 0) + Number(r.amount ?? 0);
    }
    const summary = {
      organization_id,
      window_days: days,
      total_orders: rows.length,
      paid_orders: paid.length,
      gross_revenue_by_currency: byCurrency
    };
    return {
      content: [{ type: "text", text: JSON.stringify(summary, null, 2) }],
      structuredContent: summary
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "xzgpzbrgsxtcsktiprik";
var mcp_default = defineMcp({
  name: "siteviral-mcp",
  title: "SiteViral MCP",
  version: "0.1.0",
  instructions: "Tools for SiteViral \u2014 the creator/organization platform. Use `who_am_i` to verify connectivity, `list_my_organizations` to discover the user's orgs, then `list_org_products`, `get_org_analytics`, or `list_my_purchases` for data.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [who_am_i_default, list_my_organizations_default, list_org_products_default, list_my_purchases_default, get_org_analytics_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
