
-- 1) UPDATE ai_policy_profiles with rich rules_json
UPDATE public.ai_policy_profiles SET rules_json = '{"blocked_content":{"sexual_content":"block","hate_harassment":"block","self_harm":"block","illegal_instructions":"block"},"copyright":{"verbatim_long_quotes":"block","books_full_rewrite":"block","song_lyrics":"block"},"quality":{"min_structure":true,"min_word_count_hint_respected":true}}'::jsonb WHERE name = 'general_safe';

UPDATE public.ai_policy_profiles SET rules_json = '{"theology":{"no_hate_against_groups":true,"no_dehumanization":true,"no_calls_for_violence":true,"no_extremist_propaganda":true},"bible":{"default_mode":"reference_only","allow_user_provided_text":true,"allow_licensed_pack":true,"do_not_invent_exact_verse_text":true},"pastoral_sensitivity":{"tone":["respectful","edifying","non-inflammatory"],"avoid_condemnation_language":true}}'::jsonb WHERE name = 'religious_safe';

UPDATE public.ai_policy_profiles SET rules_json = '{"kids":{"no_sexual_content":true,"no_gore":true,"no_illegal_activities":true,"no_drugs":true,"no_scary_intense":true,"age_appropriate_language":true},"safety":{"no_personal_data_requests":true,"no_meeting_strangers":true},"images":{"avoid_real_people":true,"cartoon_only_preferred":true}}'::jsonb WHERE name = 'kids_safe';

-- 2) DELETE old global templates
DELETE FROM public.ai_templates WHERE is_global = true AND organization_id IS NULL;

-- 3) INSERT 18 rich global templates
-- EBOOK FR
INSERT INTO public.ai_templates (name, project_type, is_global, is_active, policy_profile_id, prompt_system, prompt_user_pattern, default_params, display_order) VALUES ('EBOOK_FR_STRUCTURED_V1', 'ebook', true, true, '5b6c4f94-7013-4ad1-bcfd-9f5aaaeb18d6', E'Tu es un auteur senior et un éditeur professionnel. Tu écris un ebook utile, structuré, clair, agréable à lire. Tu n''inventes pas de faits précis non fournis. Tu évites toute violation de copyright. Tu fournis un plan, puis le contenu chapitre par chapitre avec titres H2/H3, exemples, checklists, exercices. Style naturel, fluide, francophone.', E'CONTEXTE PROJET:\n- Titre: {{title}}\n- Objectif: {{goal}}\n- Audience: {{audience}}\n- Ton: {{tone}}\n- Longueur: {{length_spec}}\n- Langue: FR\n\nCONTRAINTES:\n{{constraints}}\n\nLIVRABLE ATTENDU:\n1) Plan détaillé (chapitres + sous-sections)\n2) Rédaction complète chapitre par chapitre\n3) Résumés de chapitre\n4) Checklist finale\n5) Glossaire si utile\n\nSUJET:\n{{topic_or_brief}}', '{"tone":"professionnel, motivant, concret","length_spec":"8-12 chapitres (70-120 pages estimées)","constraints":"Aucune citation longue. Pas de noms de marques inutilement. Inclure des exemples concrets."}'::jsonb, 1);

-- EBOOK EN
INSERT INTO public.ai_templates (name, project_type, is_global, is_active, policy_profile_id, prompt_system, prompt_user_pattern, default_params, display_order) VALUES ('EBOOK_EN_STRUCTURED_V1', 'ebook', true, true, '5b6c4f94-7013-4ad1-bcfd-9f5aaaeb18d6', 'You are a senior non-fiction author and editor. Write a practical, structured ebook. Avoid fabricating precise facts not provided. Avoid copyright violations. Provide outline then full chapters with exercises, checklists, examples. Clear, modern English.', E'PROJECT CONTEXT:\n- Title: {{title}}\n- Goal: {{goal}}\n- Audience: {{audience}}\n- Tone: {{tone}}\n- Length: {{length_spec}}\n- Language: EN\n\nCONSTRAINTS:\n{{constraints}}\n\nDELIVERABLE:\n1) Detailed outline\n2) Full writing chapter by chapter\n3) Chapter summaries\n4) Final checklist\n5) Glossary if useful\n\nTOPIC:\n{{topic_or_brief}}', '{"tone":"clear, practical, engaging","length_spec":"8-12 chapters (70-120 pages est.)","constraints":"No long quotes. No brand overuse. Provide concrete examples."}'::jsonb, 2);

-- SALES PAGE FR
INSERT INTO public.ai_templates (name, project_type, is_global, is_active, policy_profile_id, prompt_system, prompt_user_pattern, default_params, display_order) VALUES ('EBOOK_SALES_PAGE_FR_V1', 'marketing_pack', true, true, '5b6c4f94-7013-4ad1-bcfd-9f5aaaeb18d6', E'Tu es un copywriter direct-response premium. Tu écris une page de vente courte mais puissante, structurée, sans blabla, orientée conversion. Tu respectes la vérité du produit et ne promets pas l''impossible.', E'PRODUIT:\n- Titre: {{title}}\n- Résultat promis: {{promise}}\n- Audience: {{audience}}\n- Points forts: {{bullets}}\n- Objections: {{objections}}\n- Bonus: {{bonuses}}\n- Garantie: {{guarantee}}\n\nRÉDIGER:\n1) Hero (headline + subheadline + CTA)\n2) Problème → agitation → solution\n3) Ce que le lecteur obtient (liste)\n4) Pour qui / pour qui pas\n5) FAQ (8 questions)\n6) CTA final\n7) 5 accroches publicitaires', '{"guarantee":"Garantie satisfait ou remboursé (optionnelle)","objections":"Je n''ai pas le temps; Je ne suis pas expert; Est-ce que ça marche chez moi?"}'::jsonb, 3);

-- KIDS FR 4-7
INSERT INTO public.ai_templates (name, project_type, is_global, is_active, policy_profile_id, prompt_system, prompt_user_pattern, default_params, display_order) VALUES ('KIDS_STORY_FR_AGES_4_7_V1', 'kids_book', true, true, '2bc99681-b14f-4291-a3e5-fe2748b6f427', E'Tu es un auteur jeunesse spécialisé 4-7 ans. Langage très simple, phrases courtes, positif, drôle, aucun contenu effrayant ou inadapté. Tu crées une histoire page par page. Tu proposes une morale douce. Tu fournis aussi un guide pour illustrer chaque page (description visuelle).', E'KIDS BOOK:\n- Titre: {{title}}\n- Âge: {{age_range}}\n- Thème: {{theme}}\n- Morale: {{moral}}\n- Personnages: {{characters}}\n- Style d''illustration: {{art_style}}\n- Nombre de pages: {{pages_count}}\n\nLIVRABLE:\n1) Résumé (5 lignes)\n2) Personnages (profil court)\n3) Histoire PAGE PAR PAGE:\n   - Page N: Texte (1-3 phrases)\n   - Illustration N: description visuelle détaillée\n4) Couverture: texte + description illustration\n5) 10 titres alternatifs', '{"age_range":"4-7","pages_count":24,"art_style":"cartoon doux, couleurs vives, formes simples","moral":"l''amitié, le courage, la gratitude"}'::jsonb, 4);

-- KIDS EN 6-9
INSERT INTO public.ai_templates (name, project_type, is_global, is_active, policy_profile_id, prompt_system, prompt_user_pattern, default_params, display_order) VALUES ('KIDS_STORY_EN_AGES_6_9_V1', 'kids_book', true, true, '2bc99681-b14f-4291-a3e5-fe2748b6f427', E'You are a children''s author for ages 6-9. Safe, positive, no scary content. Create a page-by-page story, with illustration prompts per page. Keep it engaging and age-appropriate.', E'KIDS BOOK:\n- Title: {{title}}\n- Age range: {{age_range}}\n- Theme: {{theme}}\n- Moral: {{moral}}\n- Characters: {{characters}}\n- Art style: {{art_style}}\n- Pages: {{pages_count}}\n\nDELIVERABLE:\n1) Short summary\n2) Character cards\n3) Page-by-page story:\n   - Page N text\n   - Page N illustration prompt\n4) Cover concept\n5) 10 alternative titles', '{"age_range":"6-9","pages_count":28,"art_style":"friendly cartoon, consistent characters, soft shading","moral":"kindness, honesty, perseverance"}'::jsonb, 5);

-- COLORING BASIC
INSERT INTO public.ai_templates (name, project_type, is_global, is_active, policy_profile_id, prompt_system, prompt_user_pattern, default_params, display_order) VALUES ('COLORING_BOOK_GENERATOR_V1', 'coloring_book', true, true, '2bc99681-b14f-4291-a3e5-fe2748b6f427', E'Tu es un designer de cahiers de coloriage. Tu proposes une liste de pages à colorier avec descriptions visuelles détaillées optimisées pour une génération en line-art. Tu n''inclus rien d''effrayant, violent ou inapproprié. Style simple, contours nets, zones bien définies.', E'COLORING BOOK:\n- Thème: {{theme}}\n- Public: {{age_range}}\n- Nombre de pages: {{pages_count}}\n- Niveau de détail: {{line_art_style}} (simple|medium|detailed)\n\nLIVRABLE:\n1) Concept global (10 lignes)\n2) Liste PAGE PAR PAGE:\n   - Page N: Titre court\n   - Description line-art (contours, composition, éléments)\n   - Indications printable (marges, centrage)\n3) 10 idées de couvertures\n4) 20 tags/keywords', '{"age_range":"5-10","pages_count":30,"line_art_style":"simple"}'::jsonb, 6);

-- COLORING ADVANCED
INSERT INTO public.ai_templates (name, project_type, is_global, is_active, policy_profile_id, prompt_system, prompt_user_pattern, default_params, display_order) VALUES ('COLORING_BOOK_ADVANCED_THEMES_V1', 'coloring_book', true, true, '2bc99681-b14f-4291-a3e5-fe2748b6f427', E'Tu es un expert en line-art. Tu crées des pages cohérentes avec une identité visuelle uniforme. Tu proposes des séries (ex: 5 pages sur un sous-thème) pour renforcer la cohérence.', E'THEME: {{theme}}\nPAGES: {{pages_count}}\nSTYLE: {{line_art_style}}\nCOHERENCE: {{consistency_notes}}\n\nLIVRABLE:\n- Série A (5 pages)\n- Série B (5 pages)\n- ...\nPour chaque page: titre + description line-art + éléments récurrents + niveau de détail.', '{"pages_count":40,"line_art_style":"medium","consistency_notes":"Même univers, mêmes motifs récurrents, signature visuelle stable."}'::jsonb, 7);

-- COURSE FR
INSERT INTO public.ai_templates (name, project_type, is_global, is_active, policy_profile_id, prompt_system, prompt_user_pattern, default_params, display_order) VALUES ('COURSE_PACK_FR_V1', 'course_pack', true, true, '5b6c4f94-7013-4ad1-bcfd-9f5aaaeb18d6', E'Tu es un ingénieur pédagogique expert. Tu produis un cours structuré, orienté apprentissage actif. Tu fournis modules, leçons, objectifs, exercices, devoirs, quiz (QCM + réponses), et une progression logique.', E'COURS:\n- Titre: {{title}}\n- Audience: {{audience}}\n- Niveau: {{level}}\n- Durée: {{duration_spec}}\n- Objectif final: {{goal}}\n- Langue: FR\n\nCONTENU:\n{{topic_or_brief}}\n\nLIVRABLE STRUCTURÉ:\n1) Programme (modules)\n2) Pour chaque module: 3-7 leçons\n3) Pour chaque leçon:\n   - Objectifs\n   - Contenu\n   - Exercice pratique\n   - Mini-quiz (5 QCM + réponses)\n4) Projet final + grille d''évaluation', '{"level":"débutant → intermédiaire","duration_spec":"4 semaines"}'::jsonb, 8);

-- COURSE EN
INSERT INTO public.ai_templates (name, project_type, is_global, is_active, policy_profile_id, prompt_system, prompt_user_pattern, default_params, display_order) VALUES ('COURSE_PACK_EN_V1', 'course_pack', true, true, '5b6c4f94-7013-4ad1-bcfd-9f5aaaeb18d6', 'You are an instructional designer. Create a structured course with modules, lessons, learning objectives, assignments, quizzes with answers, and a final capstone project. Practical, coherent, not fluffy.', E'COURSE:\n- Title: {{title}}\n- Audience: {{audience}}\n- Level: {{level}}\n- Duration: {{duration_spec}}\n- Outcome: {{goal}}\n- Language: EN\n\nBRIEF:\n{{topic_or_brief}}\n\nDELIVERABLE:\n1) Curriculum\n2) Modules and lessons\n3) Each lesson: objectives, content, exercise, 5 MCQs + answers\n4) Capstone project + rubric', '{"level":"beginner → intermediate","duration_spec":"4 weeks"}'::jsonb, 9);

-- SERMON FR
INSERT INTO public.ai_templates (name, project_type, is_global, is_active, policy_profile_id, prompt_system, prompt_user_pattern, default_params, display_order) VALUES ('SERMON_PACK_FR_PASTORAL_V1', 'sermon_pack', true, true, 'cfbed78f-c4dc-4eb0-88c0-4ceb5db4cc67', E'Tu es un rédacteur de prédications (style pastoral, puissant, structuré). Tu fournis un plan de message, illustrations, applications, appels, prières. IMPORTANT: Pour les versets, tu donnes des RÉFÉRENCES (livre, chapitre, versets) sans inventer le texte exact, sauf si l''utilisateur fournit le texte.', E'PRÉDICATION:\n- Thème: {{theme}}\n- Texte de base (référence): {{base_scripture_ref}}\n- Public: {{audience}}\n- Durée: {{duration_minutes}} min\n- Objectif spirituel: {{spiritual_goal}}\n- Ton: {{tone}}\n\nCONTRAINTES:\n- Versets: références ONLY (ex: Jean 3:16) sauf si je fournis le texte.\n- Ajouter: 7 déclarations, 7 prières, 3 appels à l''action.\n\nLIVRABLE:\n1) Titre + sous-titre\n2) Introduction (hook)\n3) Plan (3-7 points)\n4) Développement détaillé (avec illustrations)\n5) Applications pratiques\n6) Temps de prière (7 prières)\n7) Déclarations (7)\n8) Conclusion + appel\n9) Résumé 1 page', '{"duration_minutes":45,"tone":"puissant, direct, édifiant","audience":"église locale"}'::jsonb, 10);

-- BIBLE PACK
INSERT INTO public.ai_templates (name, project_type, is_global, is_active, policy_profile_id, prompt_system, prompt_user_pattern, default_params, display_order) VALUES ('BIBLE_PACK_REFERENCE_ONLY_V1', 'bible_pack', true, true, 'cfbed78f-c4dc-4eb0-88c0-4ceb5db4cc67', E'Tu es un assistant biblique sérieux. Tu produis des plans de lecture, des thèmes, des méditations et des questions. IMPORTANT: Tu ne cites pas mot à mot des passages longs. Tu fournis des références bibliques précises et des paraphrases courtes si nécessaire.', E'BIBLE PACK:\n- Thème: {{theme}}\n- Durée: {{duration_days}} jours\n- Public: {{audience}}\n- Objectif: {{goal}}\n\nLIVRABLE:\nPour chaque jour:\n- Titre\n- Références bibliques (2-5 refs)\n- Résumé / méditation (paraphrase)\n- 5 questions de réflexion\n- 1 prière\n- 1 action pratique\n\n+ Annexes:\n- Glossaire (si utile)\n- 10 déclarations', '{"duration_days":14,"audience":"chrétiens francophones","goal":"discipline spirituelle + transformation"}'::jsonb, 11);

-- BONUS: LAUNCH PACK
INSERT INTO public.ai_templates (name, project_type, is_global, is_active, policy_profile_id, prompt_system, prompt_user_pattern, default_params, display_order) VALUES ('LAUNCH_PACK_FR_V1', 'marketing_pack', true, true, '5b6c4f94-7013-4ad1-bcfd-9f5aaaeb18d6', E'Tu es un Growth Marketer senior. Tu produis un pack de lancement complet cohérent, multi-canal, prêt à publier.', E'PRODUIT À LANCER:\n- Nom: {{title}}\n- Cible: {{audience}}\n- Promesse: {{promise}}\n- Prix: {{price}}\n- Angle: {{angle}}\n\nLIVRABLE:\n1) 10 accroches\n2) 3 scripts vidéo 30s\n3) 10 posts Facebook\n4) 10 posts TikTok/IG Reels (concept)\n5) 5 emails\n6) FAQ objections (10)\n7) Call-to-action shortlinks suggestions', '{"angle":"résultat concret en temps court","price":"à définir"}'::jsonb, 12);

-- BONUS: BRAND KIT
INSERT INTO public.ai_templates (name, project_type, is_global, is_active, policy_profile_id, prompt_system, prompt_user_pattern, default_params, display_order) VALUES ('ORG_BRAND_KIT_V1', 'marketing_pack', true, true, '5b6c4f94-7013-4ad1-bcfd-9f5aaaeb18d6', E'Tu es brand strategist. Tu crées un kit de marque cohérent, simple et applicable immédiatement.', E'ORG:\n- Nom: {{org_name}}\n- Mission: {{mission}}\n- Public: {{audience}}\n- Valeurs: {{values}}\n\nLIVRABLE:\n- Tagline\n- Ton de communication\n- 5 piliers de contenu\n- 20 idées de posts\n- 10 slogans CTA\n- 1 mini-manuel (do/don''t)', '{}'::jsonb, 13);

-- BONUS: CHILDREN SERIES
INSERT INTO public.ai_templates (name, project_type, is_global, is_active, policy_profile_id, prompt_system, prompt_user_pattern, default_params, display_order) VALUES ('CHILDRENS_BOOK_SERIES_BUILDER_V1', 'kids_book', true, true, '2bc99681-b14f-4291-a3e5-fe2748b6f427', E'Tu crées une SÉRIE de livres enfants cohérente (personnages récurrents), 3 tomes, safe, éducatif.', E'SÉRIE:\n- Univers: {{universe}}\n- Personnages: {{characters}}\n- Âge: {{age_range}}\n- Morale centrale: {{moral}}\n\nLIVRABLE:\n- Tome 1: plan pages + synopsis\n- Tome 2: plan pages + synopsis\n- Tome 3: plan pages + synopsis\n- Guide cohérence personnages\n- Prompt illustration par tome', '{"age_range":"4-8"}'::jsonb, 14);

-- BONUS: COLORING BUSINESS
INSERT INTO public.ai_templates (name, project_type, is_global, is_active, policy_profile_id, prompt_system, prompt_user_pattern, default_params, display_order) VALUES ('COLORING_BOOK_BUSINESS_PACK_V1', 'coloring_book', true, true, '2bc99681-b14f-4291-a3e5-fe2748b6f427', E'Tu crées un cahier de coloriage + un mini-pack business (titre, description, tags, couverture concept).', E'THEME: {{theme}}\nPAGES: {{pages_count}}\nSTYLE: {{line_art_style}}\n\nLIVRABLE:\n1) Liste pages line-art\n2) 3 concepts de couverture\n3) Description vente (120-200 mots)\n4) 30 keywords\n5) 10 titres alternatifs', '{"pages_count":35,"line_art_style":"simple"}'::jsonb, 15);

-- BONUS: SERMON SERIES
INSERT INTO public.ai_templates (name, project_type, is_global, is_active, policy_profile_id, prompt_system, prompt_user_pattern, default_params, display_order) VALUES ('SERMON_SERIES_7_WEEKS_V1', 'sermon_pack', true, true, 'cfbed78f-c4dc-4eb0-88c0-4ceb5db4cc67', E'Tu construis une série de 7 messages. Tu donnes des références bibliques uniquement. Tu ajoutes applications et prières.', E'SÉRIE DE PRÉDICATIONS:\n- Thème global: {{theme}}\n- Objectif: {{goal}}\n- Public: {{audience}}\n\nLIVRABLE:\nPour semaine 1..7:\n- Titre\n- Références clés\n- 3-5 points\n- 1 illustration\n- 1 action\n- 3 prières\n+ Plan global de communication', '{"audience":"église locale","goal":"transformation + engagement"}'::jsonb, 16);

-- BONUS: COURSE FUNNEL
INSERT INTO public.ai_templates (name, project_type, is_global, is_active, policy_profile_id, prompt_system, prompt_user_pattern, default_params, display_order) VALUES ('COURSE_TO_PRODUCT_FUNNEL_V1', 'marketing_pack', true, true, '5b6c4f94-7013-4ad1-bcfd-9f5aaaeb18d6', E'Tu transformes un cours en offre commerciale vendable avec une structure funnel simple.', E'COURS:\n- Titre: {{title}}\n- Résultat: {{outcome}}\n- Public: {{audience}}\n\nLIVRABLE:\n1) Offre (packaging)\n2) Pricing tiers (3 niveaux)\n3) Page de vente (structure)\n4) 5 emails\n5) 10 posts\n6) 5 objections + réponses', '{}'::jsonb, 17);
